apiVersion: v1
kind: Service
metadata:
  labels:
    app: jiafan-test
    app.kubernetes.io/instance: jiafan-test
    app.kubernetes.io/name: jiafan-test-app
  name: andreas-kavountzis-live-pfs
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: jiafan-test
    app.kubernetes.io/instance: jiafan-test
    app.kubernetes.io/name: jiafan-test-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: f7580aa1eb6f7176705176e201ecff4de93edafb
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/jiafan-buildah
  labels:
    app: jiafan-test
    app.kubernetes.io/instance: jiafan-test
    app.kubernetes.io/name: jiafan-test-app
    app.openshift.io/runtime: nodejs
  name: jiafan-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jiafan-test
      app.kubernetes.io/instance: jiafan-test
      app.kubernetes.io/name: jiafan-test-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jiafan-test
        app.kubernetes.io/instance: jiafan-test
        app.kubernetes.io/name: jiafan-test-app
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/synomic/jiafan-test:89c0508507b13162a6051a8f175da2a40b6ac85d
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: jiafan-test
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: jiafan-test
    app.kubernetes.io/instance: jiafan-test
    app.kubernetes.io/name: jiafan-test-app
  name: jiafan-test-app-route
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: andreas-kavountzis-live-pfs
    weight: 100
  wildcardPolicy: None
